### ISSUE TITLE
Error al hacer una prueba sobre el ejemplo_simple.php del proyecto

### ISSUE THREAD

**Issue by rodricavs** [payway-ar/sdk-php-ventaonline#38]
Hola, estoy obteniendo este error al intentar la ejecución de un pago con el ejemplo del proyecto.
Intenté cambiar la public_key y private_key por las de sandbox que figuran en la documentación de la API Decidir y sigue igual.

```
Healthcheck Service

Respuest healthcheck
object(Decidir\Healthcheck\HealthCheckResponse)#13 (6) { ["name":protected]=> NULL ["version":protected]=> NULL ["buildTime":protected]=> NULL ["dataResponse":protected]=> array(3) { ["name"]=> string(6) "resttx" ["version"]=> string(6) "v2.1.1" ["buildTime"]=> string(23) "2022-08-31T21:34:41.451" } ["field_required":"Decidir\Data\AbstractData":private]=> NULL ["field_optional":"Decidir\Data\AbstractData":private]=> NULL }

Name: resttx
Version: v2.1.1
BuildTime: 2022-08-31T21:34:41.451
--------------------------------------------
```

`Fatal error: Uncaught Decidir\Exception\SdkException: not_found_error in C:\xampp\htdocs\sdk-php-ventaonline-master\Decidir\lib\Data\Response.php:11 Stack trace: #0 C:\xampp\htdocs\sdk-php-ventaonline-master\Decidir\lib\Payment\PaymentResponse.php(7): Decidir\Data\Response->__construct(Array) #1 C:\xampp\htdocs\sdk-php-ventaonline-master\Decidir\lib\Payment.php(39): Decidir\Payment\PaymentResponse->__construct(Array) #2 C:\xampp\htdocs\sdk-php-ventaonline-master\resources\ejemplo_simple.php(52): Decidir\Payment->ExecutePayment(Array) #3 {main} thrown in C:\xampp\htdocs\sdk-php-ventaonline-master\Decidir\lib\Data\Response.php on line 11`

Estoy configurando algo mal?

Muchas gracias de antemano,
Saludos.

**Comment by chgarciasys** [comment]
Hola, obtuviste alguna respuesta al respecto? estoy teniendo el mismo problema

Gracias
